### ISSUE TITLE
Table won't render

### ISSUE THREAD

**Issue by MarkCubb** [larlequin/PandocAcademic#18]
I've tried to render your sample table without success.  When I highlight the data and try to select Tools --> Pandoc Academic --> Pandoc Table, the Pandoc Table option is greyed out.  Thoughts?

**Comment by MarkCubb** [comment]
I figured it out.  Thanks for this add-on.

**Comment by larlequin** [comment]
Hi Mark,

Happy that you find a solution. You are very welcome for the plugin.

Best,

Guillaume
