### ISSUE TITLE
Where do the files output

### ISSUE THREAD

**Issue by vongoh** [larlequin/PandocAcademic#22]
Sorry, can't seem to find anything in the docs that tell us where the default output for a conversion goes - nor how to set that for ourselves.  Thanks.

**Comment by larlequin** [comment]
Hi,

Thank you for your interest in PandocAcademic. The output files are generated in the same folder as the source file (in markdown). For the moment, there is no option to change the output directory. However, you could change this behavior in line 161 of the main script (PandocConvertor.py):  'filepath = os.path.splitext(file_name)[0]' and change the destination.

Thanks,

Guillaume
